name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv pip install -e ".[test]"
        
    - name: 运行测试
      run: |
        pytest --cov
        
    - name: 上传覆盖率报告
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: 构建Docker镜像
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: hello_svc:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 